AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'test/**/test_*.rb'

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NilLambda:
  Enabled: true
Style/RedundantArgument:
  Enabled: true

Style/HashExcept:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/BlockAlignment:
  Enabled: false
