AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'test/**/test_*.rb'

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false
