exclude:
  flutter:
    - PluginPubspecEffectiveDartCheck
    - PluginDirectoriesCheck
    - PluginPubspecLintsCheck
  android:
    - PluginGradleAndroidPackageCheck
  ios:
    - PluginPodspecVersionCheck
    - PluginPodspecNameCheck
