name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rubocop:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop checks
        run: bundle exec rake rubocop

  tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '8'
      - name: Download Gradle
        run: wget https://services.gradle.org/distributions/gradle-7.0-bin.zip -O /opt/gradle.zip
      - name: Unzip Gradle
        run: unzip /opt/gradle.zip && export PATH=$PATH:/opt/gradle/gradle-7.0/bin
      - name: Add Gradle to PATH
        run: PATH=$PATH:/opt/gradle/gradle-7.0/bin
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failedThreshold: 90
